articles/articles/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.web.urls')),
]

articles/articles/web/urls.py
from django.urls import path

from articles.web.views import ArticlesListView, ArticleCreateView, SourceCreateView, SourcesListView, SourceDetailsView

urlpatterns = (
    path('', ArticlesListView.as_view(), name='index'),
    path('articles/create/', ArticleCreateView.as_view(), name='create article'),
    path('sources/', SourcesListView.as_view(), name='list sources'),
    path('sources/<int:pk>', SourceDetailsView.as_view(), name='details source'),
    path('sources/create/', SourceCreateView.as_view(), name='create source'),
)

articles/articles/web/models.py
from django.db import models


# Create your models here.


class Source(models.Model):
    name = models.CharField(
        max_length=50,
    )
    url = models.URLField(
        max_length=200,
    )

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(
        max_length=100,
    )
    description = models.TextField()
    image_url = models.URLField(
        max_length=200,
    )
    source = models.ForeignKey(Source, on_delete=models.CASCADE)

articles/articles/web/views.py
from django.urls import reverse_lazy, reverse
from django.views import generic as views


# Create your views here.
from django.views.generic.detail import SingleObjectMixin

from articles.web.models import Article, Source


class ArticleCreateView(views.CreateView):
    model = Article
    template_name = 'web/create-article.html'
    success_url = reverse_lazy('index')
    fields = '__all__'


class SourceCreateView(views.CreateView):
    model = Source
    template_name = 'web/create-source.html'
    # success_url = reverse_lazy('index')
    fields = '__all__'

    def get_success_url(self):
        return reverse('details source', kwargs={
            'pk': self.object.id
        })


class ArticlesListView(views.ListView):
    model = Article
    template_name = 'web/list-articles.html'


class SourceDetailsView(SingleObjectMixin, views.ListView):
    model = Source
    template_name = 'web/details-source.html'
    object = None
    paginate_by = 3

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Source.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['source'] = self.object
        return context

    def get_queryset(self):
        return self.object.article_set.all()


class SourcesListView(views.ListView):
    model = Source
    template_name = 'web/list-sources.html'

articles/templates/web/create-article.html
{% extends 'shared/base.html' %}
{% block content %}
    <div class="article-create-section">
        <div class="article-create-container container">
            <h1>Create a new Article</h1>
            <form method="post" action="{% url 'create article' %}">
                {% csrf_token %}
                 {{ form }}
                <input class="btn" type="submit" value="Create Article">
            </form>
        </div>
    </div>
{% endblock %}

articles/templates/web/create-source.html
{% extends 'shared/base.html' %}
{% block content %}
    <div class="source-create-section">
        <div class="source-create-container container">
            <h1>Create a new Source</h1>
            <form method="post" action="{% url 'create source' %}">
                {% csrf_token %}
                {{ form }}
                <input class="btn" type="submit" value="Create Source">
            </form>
        </div>
    </div>
{% endblock %}

articles/templates/web/details-source.html
{% extends 'shared/base.html' %}
{% block content %}
    <div class="source-details-section">
        <div class="source-details-container container">
            <h2>Source: {{ source.name }}</h2>
            <ol>
                {% for article in page_obj.object_list %}
                    <div class="article-card">
                        <h3 class="article-title small">{{ article.id }}{{ article.title }}</h3>
                        <img class="article-image large"
                             src="{{ article.image_url }}">
                        <p>{{ article.description }}</p>
                        <span class="source">{{ source.name }}</span>
                    </div>
                {% endfor %}

            </ol>
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ page_obj.previous_page_number }}">prev</a>
                    {% else %}
                        <a href="" style="pointer-events: none">prev</a>
                    {% endif %}
                    <span class="current">
                        {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ page_obj.next_page_number }}">next</a>
                    {% else %}
                        <a href="" style="pointer-events: none">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}

articles/templates/web/list-articles.html
{% extends 'shared/base.html' %}
{% block content %}
    <div class="home-page-section">
        <div class="home-page-container container">
            {% for article in article_list %}
                <div class="article-card">
                    <h1 class="article-title">{{ article.title }}</h1>
                    <img class="article-image" src="{{ article.image_url }}">
                    <p>{{ article.description }}</p>
                    <span class="source">{{ article.source.name }}</span>
                </div>
            {% endfor %}


        </div>
    </div>
{% endblock %}

articles/templates/web/list-sources.html
{% extends 'shared/base.html' %}
{% block content %}
    <div class="source-list-section">
        <div class="source-list-container container">
            <h2>All Sources</h2>

            {% for source in source_list %}
                <div class="source-item-card">
                    <h3>{{ source.name }}</h3>
                    <a href="{% url 'details source' source.id %}">See related articles</a>
                    <p>Link: <a href="{{ source.url }}" target="_blank">{{ source.name }}</a></p>
                </div>
            {% endfor %}


        </div>
    </div>
{% endblock %}